
# Supabase configuration for Slidecraft
# Generated for local development
project_id = "igspkppkbqbbxffhdqlq"

[api]
port = 54321
schemas = ["public", "content", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
port = 54323

[inbucket]
port = 54324

[storage]
file_size_limit = "50MiB"

[storage.buckets.fonts]
public = true
objects_path = "buckets/fonts"

[storage.buckets.uploads]
public = false
objects_path = "buckets/uploads"

[auth]
site_url = "https://igspkppkbqbbxffhdqlq.supabase.co"
additional_redirect_urls = [
  "https://*-supabase.vercel.app/*/*",
  "https://supabase.com/*/*",
  "https://*.lovable.app/*/*",
]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.external.github]
enabled = false
client_id = "env(GITHUB_CLIENT_ID)"
secret = "env(GITHUB_SECRET)"
redirect_uri = "http://localhost:54321/auth/v1/callback"

[auth.external.apple]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

# Public edge functions
[functions.hubspot_client_id]
verify_jwt = false

[functions.hubspot_oauth_callback]
verify_jwt = false

[functions.section-templates]
verify_jwt = false

[functions.slide-templates]
verify_jwt = false

[functions.hubspot_fetch_contacts]
verify_jwt = true

[functions.post_note]
verify_jwt = true

[functions.hubspot_tokens]
verify_jwt = true

[functions.search_contacts]
verify_jwt = true

[functions.sections]
verify_jwt = true

[functions.blueprints]
verify_jwt = true

[functions.generate-slides]
verify_jwt = true

[functions.clerk-webhook]
verify_jwt = false

[functions.process-presentation-request]
verify_jwt = true

[auth.third_party.clerk]
enabled = true
domain = "https://ideal-lion-39.clerk.accounts.dev/"

# Authenticated edge functions use default verify_jwt = true
