name: Delete codex branch

on:
  pull_request:
    types:
      - closed

permissions:
  contents: write

jobs:
  delete_branch:
    if: ${{ github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'codex') }}
    runs-on: ubuntu-latest
    steps:
      - name: Delete head branch
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const isFork = pr.head.repo.full_name !== pr.base.repo.full_name;
            if (isFork) {
              core.info('Pull request is from a fork; skipping branch deletion.');
            } else {
              await github.rest.git.deleteRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `heads/${pr.head.ref}`
              });
              core.info(`Deleted branch ${pr.head.ref}`);
            }

